from collections import Counter

goodWords='''
nice considerate pleasant fine great excellent virtuous pure  respectable delicious taste beauty idi. honorable best skill happy friendly glad worthy cool wonderful right appropriate proper benevolent kind person much
real usual upright benefit blessing godsend allright satisfactory agreed alright sure expected cute feature attractiveness sweet smell well greatest just fair finest top-drawer improved sound authentic profitable favorable moral honest helpful useful splendid kindly welcome greater lovely super favourable sociable correct handsome groovy agreeable appearance okay safe suitable decent beautiful perfect positive better improve advanced righteous congenial pretty look clean pleasing enjoyable Findexcellentthesaurus TellmyfriendsaboutPowerThesaurus effect greatness really benign advantageous prettygood imperfection grateful tasty amazing quality awesome rather superior gorgeous superb quite beneficial valuable advantage affluence sympathetic goodly successful power happiness pleasurable adequate help luck pleasure evil genial charitable generous humanitarian skilled competent terrific int. fantastic nicely reallygood estimable salubrious nourishing high success effective valid genuine acceptable delightful kindness understanding properly verywell assent true healthy energetic positivefeelings attheright brilliant bright wholesome honourable badly love dear goodfeeling tender satisfying profit boon gain desirable noble amiable goodness worth gentle exquisite morality outstanding attractive charming perks poorly beneficent behaviour chaste yummy action major terrible further greatdeal ethical sake lucky good-natured betteroff gratifying kindhearted interest worthwhile comfortable delighted clever able large amount big fresh smart marvelous positively goodthing miracle pleased feeling well-disposed welfare gracious cordial palatable extraordinary substantial sick white ideal skilful qualified ability capable reliable trustworthy flawless unblemished spotless supportive principled first-rate felicitous fabulous favor adequately poor correctly humane bonny considerable comfort rich thing owned solid commendable affable grand well-being handy relevant fit sufficient long behave enhanced finer enjoy
'''


badWords='''
reallybad  verybadly prettybad terrible medical sickness toobad realbad awful afraid horrible appalling sobad verypoorly atrocious nasty verypoor outrageous worthless disgraceful Findexcellentthesaurus TellmyfriendsaboutPowerThesaurus lousy disgusting hate abysmal poor negative miserable reallymean veryugly verywrong flagrant hideous grueling wretched it'sawful swearing bad it'sbad ghastly reallyhurt verynasty reallynasty reallyugly rotten frightful abominable gross horrendous odious shocking dreadful awfuljob damn hurtalot reallybadly verymean realugly beastly flagitious heinous monstrous ungodly wicked dire damnable grievous gruesome tragic vicious execrable hellish tragical woeful notgoodenough horrid verylow verysick reallywrong reallysick extremelypoor lotofpain verythin veryevil verywicked verynaughty reallymessedup verymessy highlynegative verybadthing reallysucked reallyweak prettymessed foul antisocial shoddy despicable almighty grisly tremendous splitting mortal perishing chronic cruel deadly deuced direful darn dread ferocious morbid parlous towering unholy crashing frightening ghastful harrowing immane helluva grizzly howling woesome terrifying hairraising gastful spine-chilling dreaded scathing unsettling doggone enormous fearful scarey awfulwork terriblejob terriblework thisisterriblework you'reafool you'reidiot you'renotsmart youdidbad angry nogood veryangry veryupset reallypainful verypainful prettynasty ugly extremelybad veryharmful verydetrimental extremelyharmful reallyconfused
reallyhurts verydirty quitebadly reallybadthing inaverybad verynegatively veryseriousthing notgoodatall prettybadshape reallybadplace reallylousy verybadshape verypoorstate reallybadshape realnasty verybadway extremelybadly veryunwell unsatisfactory inferior slovenly pathetic useless low unfortunate desolate disapproving wrong contemptible blatant godawful hair-raising repulsive loathsome yukky crummy baddoing badjob badwork severe
dull unpleasant grouchy inabadmood worst veryseriously reallydumb veryrough reallyhurting veryweak veryfaint veryunpleasant mostunpleasant verynegative extremelynegative sonasty feelingterrible badboy so-so
'''

def process(wordlist):
    wordlist = wordlist.split("\n")
    for i in range(0,len(wordlist)-1):
        wordlist[i] = ''.join(wordlist[i])
    uni = Counter(wordlist)
    words = ' '.join(uni.keys())
    print(uni)

process(goodWords)